### PR TITLE
fix: serialize buffer size check

### LINKED ISSUE #46: Assertion Failed on Terraform Files
### Problem
I am getting the following error when trying to navigate in the nvim editor, on a terraform file, either typing or basic operation throws this and returns me back to the shell:
```Assertion failed: (length <= TREE_SITTER_SERIALIZATION_BUFFER_SIZE), function ts_parser__external_scanner_serialize, file parser.c, line 404```

### Reference
https://github.com/tree-sitter/tree-sitter/issues/3406

### Steps to reproduce

My configuration is just using the default AstroNVim installation.
```
git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
rm -rf ~/.config/nvim/.git
nvim
```
and from here on when i try editing a terraform file it just randomly starts crashing. I've tried using different distros of vim but seems to be still facing the same issue.

### Expected behavior

It should not crash.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

macOS 14.5

### PR DESCRIPTION
**Pull request by MichaHoffmann**
During the check that we dont overflow the serialization buffer we erroneously checked with size(uint32_t) == 1 which could cause us to crash with some input strings.

might fix #46

### CODE REVIEW

**Review by amaanq — APPROVED** [review]

**Comment by clason** [comment]
@amaanq This change doesn't compile.

**Comment by MichaHoffmann** [comment]
> @amaanq This change doesn't compile with `tree-sitter build` (nor with nvim-treesitter flags).

Oh sorry! We should add a CI pass for that. What are the flags and the compiler again? I'll see ti fixing it after work today.

**Comment by clason** [comment]
Just `tree-sitter build` will do the trick. (You might wish to rewrite the scanner to use the new headers you get with `tree-sitter generate` -- @amaanq should be able to do this quickly, he has practice ;))

**Comment by clason** [comment]
You could also use the upstream workflow while you're at it: https://github.com/tree-sitter-grammars/template/tree/master/.github/workflows

**Comment by MichaHoffmann** [comment]
Weird, I did run the tests and all multiple times using the tree sitter cli, I wonder why build should break if the compilation for tests worked.

**Comment by clason** [comment]
Which CLI version?

**Comment by MichaHoffmann** [comment]
```
 fedora  ~  git  tree-sitter-hcl   mhoffmann/fix-size-accounting-check-in-serialize   
$ tree-sitter build
 fedora  ~  git  tree-sitter-hcl   mhoffmann/fix-size-accounting-check-in-serialize   
$ tree-sitter
tree-sitter 0.22.5
...
```

**Comment by clason** [comment]
Could be compiler version-specific, of course. (Latest CLI -- and the one we test with -- is 0.22.6.)

File: src/scanner.c [hunk 1]
```diff
@@ -84,12 +84,12 @@ enum TokenType {
...
 };
 
-enum ContextType {
+typedef enum ContextType {
     TEMPLATE_INTERPOLATION,
     TEMPLATE_DIRECTIVE,
     QUOTED_TEMPLATE,
     HEREDOC_TEMPLATE,
-};
+} ContextType;
```
Comment (clason) [inline src/scanner.c:92]: You're missing these changes in the terraform scanner.

**Comment by clason** [comment]
I just pushed a fixup with the missing changes.

File: src/scanner.c (hunk 1 above)
Comment (MichaHoffmann) [reply src/scanner.c:92]: :see_no_evil: that explains it; sorry and thank you! Is there a way to handle the terraform scanner more elegantly? I put it there because at the time nvim-treesitter didnt allow having queries for multiple filetypes with one parser.

Comment (clason) [reply src/scanner.c:92]: If it's really the same parser, you can register it for other filetypes with `vim.treesitter.language.register()`.

Comment (MichaHoffmann) [reply src/scanner.c:92]: Queries differ somewhat ( there used to be only one, but then there were some complaints that some strings got highlighted as terraform keywords in other hcl based languages like for packer or whatnot, so i split it into generic hcl and then terraform iirc )

Comment (clason) [reply src/scanner.c:92]: Then I think this is the best for now (until upstream tree-sitter adds dedicated "dialect" support).
